server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#actuator related changes start for circuitbreakers
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#actuator related changes end

#circuitbreaker resilience4j related changes start
resilience4j:
  circuitbreaker:
    instances:
      hotelRatingBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
  retry:
    instances:
      hotelRatingRetryServic:
        max-attempts: 3
        wait-duration: 3s
        
  ratelimiter:
    instances:
      hotelRatingRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

#circuitbreaker resilience4j related changes end
        
    
     